package com.example.administrator.myapplication.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.myapplication.Model.UserInfo;
import com.example.administrator.myapplication.Model.CheckinInfo;

import com.example.administrator.myapplication.greendao.UserInfoDao;
import com.example.administrator.myapplication.greendao.CheckinInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig checkinInfoDaoConfig;

    private final UserInfoDao userInfoDao;
    private final CheckinInfoDao checkinInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        checkinInfoDaoConfig = daoConfigMap.get(CheckinInfoDao.class).clone();
        checkinInfoDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        checkinInfoDao = new CheckinInfoDao(checkinInfoDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(CheckinInfo.class, checkinInfoDao);
    }
    
    public void clear() {
        userInfoDaoConfig.clearIdentityScope();
        checkinInfoDaoConfig.clearIdentityScope();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public CheckinInfoDao getCheckinInfoDao() {
        return checkinInfoDao;
    }

}
